exp_name: 'baseline'
device: "cuda"
seed: 20
json_files: ["data/AudioCaps/json_files/train.json", "data/Clotho/json_files/train.json"]
blacklist: "data/json_files/blacklist/blacklist_exclude_test_ac.json"
pretrain_path: "/project/mc232/mm2356/WavCaps/captioning/outputs/pretrain_baseline_run3_lr_5e-05_seed_20/models/clotho_best_model.pt"
pretrain_dir: "/project/mc232/mm2356/WavCaps/captioning/outputs/pretrain_baseline_run3_lr_5e-05_seed_20/models"


audio_args:
  sr: 32000
  n_fft: 1024
  hop_length: 320
  f_min: 50
  f_max: 14000
  n_mels: 64
  max_length: 10
  mono: True


data_args:
  dataset: "Clotho, Audiocaps"
  batch_size: 32
  num_workers: 8


audio_encoder_args:
  model_arch: "transformer"
  model_name: "htsat"
  pretrained: True
  freeze: false
  spec_augment: True


text_decoder_args:
  name: "facebook/bart-base"
  pretrained: true
  bert_args:
    attention_probs_dropout_prob: 0.2
    hidden_act: "gelu"
    hidden_dropout_prob: 0.2
    hidden_size: 768
    initializer_range: 0.02
    intermediate_size: 2048
    layer_norm_eps: !!float 1e-5
    max_position_embeddings: 128
    model_type: "bert"
    num_attention_heads: 8
    num_hidden_layers: 4
    add_type_embeddings: false
    vocab_size: 30522
    add_cross_attention: true
    is_decoder: true
    num_labels: 0
    name: "bert-base-uncased"


optim_args:
  scheduler: cosine
  lr: !!float 5e-6
  warmup_steps: 6400
  optimizer_name: "adam"
  betas: [0.9, 0.999]
  eps: !!float 1e-8
  momentum: 0.9
  gamma: 0.1
  warmup_epochs: 2
  step_epochs: 10
  weight_decay: !!float 1e-6


training:
  epochs: 20
  clip_grad: 2
  dropout: 0.2
